version: '2.4'

services:
  nginx-proxy:
    container_name: nginx
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
    mem_limit: 100m
    mem_reservation: 50m
    cpus: 0.3
    environment:
      - TZ=Asia/Singapore

  letsencrypt-nginx-proxy-companion:
    container_name: letsencrypt
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    mem_limit: 75m
    cpus: 0.1
    environment:
      - TZ=Asia/Singapore

  web1:
    container_name: "${APP_NAME}"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    ports:
      - "8888:8888"
    build:
      dockerfile: ./Dockerfile
      context: .
    mem_limit: 256m
    mem_reservation: 50m
    cpus: 0.5
    environment:
      - VIRTUAL_HOST=api.nickczj.com
      - LETSENCRYPT_HOST=api.nickczj.com
      - APP_ENV=prod
      - TZ=Asia/Singapore

  mariadb:
    container_name: "${APP_NAME}-mariadb"
    image: "mariadb:${MARIADB_VERSION}"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mariadb_data:/var/lib/mysql/data"
      - "mariadb_logs:/var/lib/mysql/logs"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--user=${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      interval: 5s
      retries: 10

volumes:
  mariadb_data:
  mariadb_logs: